### ISSUE TITLE
Support any rotation strategy

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#158]
# 🩲 Brief
Currently, we have only one rotation strategy available - retain `n` days of backups.

We should implement support for _at least_ a few other common rotation strategies:
- Retain latest weekly backup
- Retain latest monthly backup

It's very common to want to keep n days of backup, plus a weekly and a monthly so that you have the option of restoring an older backup in case your problem exists in the more recent ones because you were not able to restore within n days.

But why stop there?

## 🌐 Global vs local retention

Currently, `retention_days` is configured globally across all storage types. This is not really necessary, because each storage handler has its own `rotate()` and could support individual rotation strategies too. So maybe our user wants to do backups on both Dropbox and S3, but while his S3 has basically limitless space (because S3 is _stupidly cheap_), the Dropbox only has 100GB and our user wants to be a little bit more conservative with how much space is used there.

So, why shouldn't we let our user configure a big fat rotation policy of keeping 30+ backups on S3, but only keep 3 days worth on Dropbox?

## 🤓 Universal language for frequency

So, how can we support all of this, but without adding a ton of complexity to our config file? Thankfully, there is a simple solution, because this is pretty much a solved problem. We'll just use **[cron schedule expressions](http://crontab.guru/)**. It can succinctly express any frequency you want to keep backups at.

Here's how that might look in our config:
```yaml
storage:
  s3: # Storage type
    main_s3: # Storage identifier
      bucket: bucket
      endpoint: s3.endpoint.com
      rotation_strategies:
        - * 4 * * *   # Keep any backup made between 04:00 and 04:59, regardless of date
        - * * * * 0    # Keep any backup made on a Sunday, regardless of time or date
        - * * 1 1 *   #  Keep any backup made on the 1st of January, regardless of when it was made
        - * * * 1 *   # Keep any backup made on the 1st of any month, regardless of when it was made
    secondary_s3:
      bucket: bucket
      endpoint: s3.another_endpoint.com
  dropbox:
    main_dropbox:
      access_token: XXXXXXXXXXX
    secondary_dropbox:
      access_token: XXXXXXXXXXX
```

## ✅ Okay, so what do we do?

Listen, _Linda_, it's simple. We just:

- [ ] Continue supporting `retention_days` as a global setting, for backwards compatibility purposes. e.g., if `retention_days` is set to 7, 7 days of backup will _always_ be kept, no matter what other strategies are configured.
- [ ] Implement support for additional strategies at the Storage config level.
  - [ ] This is configured under `storage/<storage_type>/<storage_identifier>/rotation
  - [ ] This configuration parameter takes a list of cron schedule expressions
  - [ ] For each cron schedule expression, resolve the expression into a strategy we can use to identify which backups we will keep.
- [ ] Evaluate the backup storage directory using each of these additional optional strategies, as well as `retention_days`, in order to create an allowlist of which backups to keep. Delete all backups that are not in this allowlist.
